# Generated by Django 5.2.1 on 2025-07-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_candidate_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='high_school_degree',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High School Certificate/Degree'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='high_school_grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='High School Grade'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='high_school_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='High School Name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='high_school_passing_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='High School Passing Year'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='professional_experience',
            field=models.TextField(blank=True, help_text='Describe your professional experience', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='university_degree',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='University Certificate/Degree'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='university_grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='University Grade'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='University Name'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='university_passing_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='University Passing Year'),
        ),
    ]
