# Generated by Django 5.1.2 on 2025-01-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0006_company_latitude_company_longitude'),
        ('job_post', '0002_jobpost_job_location'),
        ('mail', '0001_initial'),
        ('registration', '0004_alter_candidate_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Application_Mail',
        ),
    ]
