# Generated by Django 5.1.2 on 2024-11-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_registration', '0005_alter_company_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tags', models.CharField(help_text='Comma-separated tags (max 6)', max_length=255)),
                ('job_type', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Onsite', 'Onsite')], max_length=20)),
                ('salary_range', models.CharField(max_length=50)),
                ('job_time', models.CharField(default='9am-5pm', max_length=50)),
                ('description', models.TextField()),
                ('active_recruiting', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='company_registration.company')),
            ],
        ),
    ]
