# Generated by Django 5.1.2 on 2024-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
