# Generated by Django 5.1.2 on 2025-03-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0002_jobpost_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='tags',
            field=models.TextField(help_text='Comma-separated tags'),
        ),
    ]
