# Generated by Django 5.1.2 on 2025-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0003_alter_jobpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='tags',
            field=models.CharField(help_text='Comma-separated tags (max 6)', max_length=255),
        ),
    ]
