# Generated by Django 5.1.3 on 2024-12-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_registration', '0006_company_latitude_company_longitude'),
        ('registration', '0003_alter_candidate_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(null=True)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='registration.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='company_registration.company')),
            ],
            options={
                'db_table': 'apply',
            },
        ),
    ]
