# Generated by Django 5.1.2 on 2025-03-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='application_response',
            field=models.CharField(choices=[('Application Submitted', 'Application Submitted'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Application Submitted', max_length=50),
        ),
    ]
