# Generated by Django 5.1.2 on 2025-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_apply_application_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='application_response',
            field=models.CharField(choices=[('Application Submitted', 'Application Submitted'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], max_length=50),
        ),
    ]
