# Generated by Django 5.1.2 on 2024-12-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_alter_candidate_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='gen_cv/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_cv', to='registration.candidate')),
            ],
        ),
    ]
