# Generated by Django 5.2.1 on 2025-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='dob',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='education',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='skillset',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
