# Generated by Django 5.2.1 on 2025-08-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_candidatecv_address_candidatecv_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='template_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
