# Generated by Django 5.2.1 on 2025-08-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(default='ccadminme@gmail.com', max_length=100)),
                ('admin_password', models.CharField(default='12345678', max_length=100)),
            ],
        ),
    ]
