# Generated by Django 5.1.2 on 2024-11-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='123456', max_length=255),
            preserve_default=False,
        ),
    ]
