# Generated by Django 5.1.2 on 2024-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0002_company_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(default='company', editable=False, max_length=50),
        ),
    ]
