# Generated by Django 5.1.2 on 2024-11-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_registration', '0003_company_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='type',
            new_name='user_type',
        ),
    ]
